---
version: 2
root-markers:
  - .git/

tools:
  yamllint: &yamllint
    prefix: yamllint
    lint-command: yamllint --format parsable --strict -
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: [%t%*[a-z]] %m'

  yamlfix: &yamlfix
    format-command: yamlfix -
    format-stdin: true

  jsonlint-lint: &jsonlint-lint
    prefix: jsonlint
    lint-command: jsonlint -c
    lint-stdin: true
    lint-formats:
      - 'line %l, col %c, found: %m'

  jq-format: &jq-format
    format-command: jq .
    format-stdin: true

  shfmt: &shfmt
    format-command: shfmt -i 2 -ci -s -bn -
    format-stdin: true

  eslint: &eslint
    prefix: eslint
    lint-command: npx --no-install eslint -f unix --stdin --stdin-filename ${INPUT}
    lint-ignore-exit-code: true
    lint-stdin: true
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json

  prettier: &prettier
    format-command: npx --no-install prettier --write --stdin-filepath ${INPUT}
    format-stdin: true

  nixpkgs-fmt: &nixpkgs-fmt
    format-command: nixpkgs-fmt
    format-stdin: true

languages:
  yaml:
    - <<: *yamllint
    - <<: *yamlfix

  json:
    - <<: *jq-format
    - <<: *jsonlint-lint

  javascript:
    - <<: *prettier
    - <<: *eslint

  sh:
    - <<: *shfmt

  nix:
    - <<: *nixpkgs-fmt
