function pack_delayed#plugins(...)
  packadd vim-multiple-cursors
  packadd vim-jsx-improve
  packadd vim-repeat
  packadd vim-commentary
  packadd vim-surround
  packadd vim-eunuch
  packadd hlyank.vim
  packadd vim-over
  packadd vim-easymotion
  packadd vim-choosewin
  packadd ack.vim
  packadd nerdtree
  packadd quickfix-reflector.vim
  packadd vim-prettier
  packadd ale
  packadd vim-gutentags
  packadd vim-picker
endfunction
