---
version: 2
root-markers:
  - .git/

provide-definition: true

tools:
  vim: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  eslint: &eslint
    lint-command: './node_modules/.bin/eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

  prettier: &prettier
    format-command: './node_modules/.bin/prettier ${--config-precedence:configPrecedence} ${--tab-width:tabWidth} ${--single-quote:singleQuote} ${--trailing-comma:trailingComma}'

  gprettier: &gprettier
    format-command: 'prettier ${--config-precedence:configPrecedence} ${--tab-width:tabWidth} ${--single-quote:singleQuote} ${--trailing-comma:trailingComma}'

  shfmt: &shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true
  luafmt: &luafmt
    format-command: 'luafmt --stdin'
    format-stdin: true

  jsonlint: &jsonlint
    format-command: 'jsonlint -'
    format-stdin: true

languages:
  javascript:
    - <<: *eslint
    - <<: *prettier
  typescript:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  vim:
    - <<: *vim-vint
