" Name:         Gruvbox 8 Hard
" Description:  Retro groove color scheme originally designed by morhetz
" Author:       morhetz <morhetz@gmail.com>
" Maintainer:   Lifepillar <lifepillar@lifepillar.me>
" Website:      https://github.com/lifepillar/vim-gruvbox8/
" License:      Vim License (see `:help license`)
" Last Updated: Sun Mar 20 16:00:33 2022

" Generated by Colortemplate v2.2.0

hi clear
let g:colors_name = 'gruvbox8'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link CursorColumn CursorLine
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link VisualNOS Visual
hi! link Tag Special
hi! link lCursor Cursor
hi! link iCursor Cursor
hi! link vCursor Cursor

if &background ==# 'dark'
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#282828', '#cc241d', '#98971a', '#d79921', '#458588', '#b16286', '#689d6a', '#a89984', '#928374', '#fb4934', '#b8bb26', '#fabd2f', '#83a598', '#d3869b', '#8ec07c', '#ebdbb2']
  endif
  hi Normal guifg=#ebdbb2 guibg=#282828 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#fabd2f guibg=#3c3836 gui=NONE cterm=NONE
  hi FoldColumn guifg=#928374 guibg=#3c3836 gui=NONE cterm=NONE
  hi SignColumn guifg=#ebdbb2 guibg=#3c3836 gui=NONE cterm=NONE
  hi VertSplit guifg=#665c54 guibg=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#3c3836 gui=NONE cterm=NONE
  hi Comment guifg=#928374 guibg=NONE gui=italic cterm=italic
  hi CursorLine guifg=NONE guibg=#3c3836 gui=NONE cterm=NONE
  hi Error guifg=#fb4934 guibg=#1d2021 gui=bold,reverse cterm=bold,reverse
  hi ErrorMsg guifg=#1d2021 guibg=#fb4934 gui=bold cterm=bold
  hi Folded guifg=#928374 guibg=#3c3836 gui=italic cterm=italic
  hi LineNr guifg=#494a40 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=NONE guibg=#504945 gui=bold,underline cterm=bold,underline
  hi NonText guifg=#444444 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#ebdbb2 guibg=#504945 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#504945 gui=NONE cterm=NONE
  hi PmenuSel guifg=#504945 guibg=#83a598 gui=bold cterm=bold
  hi PmenuThumb guifg=NONE guibg=#7c6f64 gui=NONE cterm=NONE
  hi SpecialKey guifg=#444444 guibg=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#ebdbb2 guibg=#3c3836 gui=NONE cterm=NONE
  hi StatusLineNC guifg=#7c6f64 guibg=#3c3836 gui=NONE cterm=NONE
  hi TabLine guifg=#7c6f64 guibg=#3c3836 gui=NONE cterm=NONE
  hi TabLineFill guifg=#7c6f64 guibg=#3c3836 gui=NONE cterm=NONE
  hi TabLineSel guifg=#ebdbb2 guibg=#3c3836 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#fbf1c7 guibg=#665c54 gui=bold cterm=bold
  hi ToolbarLine guifg=NONE guibg=#665c54 gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#393634 gui=NONE cterm=NONE
  hi WildMenu guifg=#83a598 guibg=#504945 gui=bold cterm=bold
  hi Conceal guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi DiffAdd guifg=NONE guibg=#1d2021
  hi DiffChange guifg=NONE guibg=#1d2021
  hi DiffDelete guifg=#6a3832 guibg=#1d2021
  hi DiffText guifg=NONE guibg=#161919
  hi Directory guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
  hi EndOfBuffer guifg=#3c3836 guibg=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=NONE guibg=#1b4b4a gui=NONE cterm=NONE
  hi CurSearch guifg=NONE guibg=#1b4b4a gui=NONE cterm=NONE
  hi ModeMsg guifg=#fabd2f guibg=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#fabd2f guibg=NONE gui=bold cterm=bold
  hi Question guifg=#fe8019 guibg=NONE gui=bold cterm=bold
  hi Search guifg=NONE guibg=#353834 gui=NONE cterm=NONE
  hi SpellBad guifg=#fb4934 guibg=NONE guisp=#fb4934 gui=italic,undercurl cterm=italic,underline
  hi SpellCap guifg=#83a598 guibg=NONE guisp=#83a598 gui=italic,undercurl cterm=italic,underline
  hi SpellLocal guifg=#8ec07c guibg=NONE guisp=#8ec07c gui=italic,undercurl cterm=italic,underline
  hi SpellRare guifg=#d3869b guibg=NONE guisp=#d3869b gui=italic,undercurl cterm=italic,underline
  hi Title guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
  hi WarningMsg guifg=#fb4934 guibg=NONE gui=bold cterm=bold
  hi Boolean guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
  hi Define guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi Debug guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#fb4934 guibg=#1d2021 gui=bold,reverse cterm=bold,reverse
  hi Exception guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Float guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
  hi Function guifg=#b8bb26 guibg=NONE gui=bold cterm=bold
  hi Identifier guifg=#83a598 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=fg guibg=NONE gui=NONE cterm=NONE
  hi Include guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
  hi Label guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Macro guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi Repeat guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi Structure guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=fg guibg=#1d2021 gui=bold,italic cterm=bold,italic
  hi Type guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#83a598 guibg=NONE guisp=#83a598 gui=underline cterm=underline
  hi CursorIM guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi NormalMode guifg=#a89984 guibg=#1d2021 gui=reverse cterm=reverse
  hi InsertMode guifg=#83a598 guibg=#1d2021 gui=reverse cterm=reverse
  hi ReplaceMode guifg=#8ec07c guibg=#1d2021 gui=reverse cterm=reverse
  hi VisualMode guifg=#fe8019 guibg=#1d2021 gui=reverse cterm=reverse
  hi CommandMode guifg=#d3869b guibg=#1d2021 gui=reverse cterm=reverse
  hi Warnings guifg=#fe8019 guibg=#1d2021 gui=reverse cterm=reverse

  hi GitGutterAdd guifg=#8ec07c guibg=#3c3836
  hi GitGutterChange guifg=#fabd2f guibg=#3c3836
  hi GitGutterChangeDelete guifg=#BF616A guibg=#3c3836
  hi GitGutterDelete guifg=#BF616A guibg=#3c3836
  hi ALEWarningSign guifg=#EBCB8B guibg=#3c3836
  hi ALEErrorSign guifg=#BF616A guibg=#3c3836
  hi ALEInfoSign guifg=#83a598 guibg=#3c3836
  hi link SignifySignAdd             GitGutterAdd
  hi link SignifySignChange          GitGutterChange
  hi link SignifySignChangeDelete    GitGutterChangeDelete
  hi link SignifySignDelete          GitGutterDelete
  hi link SignifySignDeleteFirstLine GitGutterDelete
  hi CocFloating guibg=#1d2021
  hi link CocCodeLens Comment
  hi link CocErrorSign ALEErrorSign
  hi link CocWarningSign ALEWarningSign
  hi link CocInfoSign ALEInfoSign
  hi link CocHintSign ALEInfoSign
  hi link CocHintLine NONE
  hi link CocErrorHighlight ALEError
  hi link CocWarningHighlight ALEWarning
  hi link CocInfoHighlight ALEInfo
  hi link CocGitAddedSign GitGutterAdd
  hi link CocGitChangeRemovedSign GitGutterChangeDelete
  hi link CocGitChangedSign GitGutterChange
  hi link CocGitRemovedSign GitGutterDelete
  hi link CocGitTopRemovedSign GitGutterDelete

  hi diffAdded guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
  hi diffRemoved guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
  hi diffChanged guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
  hi diffFile guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
  hi diffNewFile guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
  hi diffLine guifg=#83a598 guibg=NONE gui=NONE cterm=NONE

  hi link htmlEndTag htmlTag
endif

" vim: et ts=2 sw=2
